version: "2.0"
services:
  fastapi:
    image: alex6nbai/xinference_vllm:test
    expose:
      - port: 9997
    env:
      - NCCL_P2P_DISABLE=1
      - NCCL_SHM_DISABLE=1
deployment:
  fastapi:
    lagrange:
      count: 1
